"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _survey_list from './survey-list.bones.json'

registerBones({
  "survey-list": _survey_list,
})
